# Generated by Django 4.0.3 on 2022-03-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='lol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='slug',
            field=models.SlugField(default='lol'),
            preserve_default=False,
        ),
    ]
